services:

  postgres-database:
    image: postgres
    container_name: postgres-database
    ports:
      - 5432:5432
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cine-manager
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - dev

networks:

  dev:
    driver: bridge

volumes:

  data:
